import { EventEmitter } from '../../../stencil.core';
export declare class WebAudioSource {
    element: HTMLElement;
    webAudioWrapper: HTMLElement;
    src: string;
    name: string;
    inert: boolean;
    midikey: number;
    midichannel: number;
    status: string;
    effectsvolume: number;
    context: AudioContext;
    masterGain: GainNode;
    wetGain: GainNode;
    dryGain: GainNode;
    channelGain: GainNode;
    effects: Array<object>;
    source: AudioBufferSourceNode;
    buffer: AudioBuffer;
    entry: string;
    duration: number;
    startTime: number;
    pausedTime: number;
    elapsedTime: number;
    playing: boolean;
    timeupdate: EventEmitter;
    getBuffer(): AudioBuffer;
    webAudio(): HTMLElement;
    gain(place?: string): GainNode;
    getDuration(): number;
    currentTime(): number;
    prepare(): void;
    play(): void;
    skipTo(time: any): void;
    pause(): void;
    toggle(): void;
    stop(): void;
    tick(): void;
    assignBuffer(webAudio: any, buffer: any): void;
    prepareEffects(): void;
}
