export declare class Picture {
    element: HTMLElement;
    poster: string;
    large: string;
    type: "background" | "picture";
    width: number;
    height: number;
    nozoom: boolean;
    block: boolean;
    bg: string;
    alt: string;
    aspectRatio: number;
    sources: Array<any>;
    active: boolean;
    zoom: any;
    palette: any;
    figure: HTMLElement;
    componentWillLoad(): void;
    componentDidLoad(): void;
    mountZoom(): void;
    handlePosterChange(): void;
    handleActive(): void;
    medium(): Promise<any>;
    in(): Promise<void>;
    getPictureColor(): void;
    setBG(): void;
    prepareSources(): void;
    setBackgroundImage(): void;
    updateAspectRatio(): void;
    renderPicture(): any[];
    render(): any;
}
