import '../../../stencil.core';
import { EventEmitter } from "../../../stencil.core";
export declare class ToggleOption {
    element: HTMLElement;
    input: HTMLInputElement;
    type: string;
    checked: boolean;
    checkedDefault: boolean;
    single: boolean;
    icon: boolean;
    tooltip: string;
    disabled: boolean;
    for: string;
    name: string;
    default: string;
    value: string;
    required: boolean;
    inline: boolean;
    size: boolean;
    selectedCopy: string;
    _type: string;
    focused: boolean;
    blur: number;
    ease: TweenInstance;
    change: EventEmitter;
    componentWillLoad(): void;
    componentDidLoad(): void;
    updateRealType(): void;
    confirm(): Promise<void>;
    updateSelected(value: boolean): void;
    onToggleChange(e: any): void;
    onFocus(): void;
    onBlur(): void;
    onKeyUp(e: any): void;
    renderCheckbox(): JSX.Element;
    renderRadioBlock(): JSX.Element;
    renderCheckBlock(): JSX.Element;
    render(): JSX.Element;
}
