import '../../../stencil.core';
export declare class WebAudioVisualizer {
    element: HTMLElement;
    canvas: HTMLCanvasElement;
    canvasCTX: any | WebGLRenderingContext | CanvasRenderingContext2D;
    for: string;
    type: string | "wave" | "bars" | "webgl";
    smoothing: number;
    size: number;
    color: string;
    tag: HTMLAudioElement;
    freqs: Uint8Array;
    times: Uint8Array;
    width: number;
    height: number;
    context: AudioContext;
    analyser: AnalyserNode;
    renderer: AnalyserNode;
    vertex: string;
    vertexShader: string;
    fragment: string;
    fragShader: string;
    fragTime: WebGLUniformLocation;
    fragSpectrumArray: Uint8Array;
    fragSpectrum: Uint8Array;
    _bufferLength: AnalyserNode;
    _dataArray: AnalyserNode;
    componentDidLoad(): void;
    connect(context: AudioContext, destination?: any): this;
    draw(): void;
    wave(): void;
    bars(): void;
    webgl(): void;
    getFrequencyValue(freq: any): number;
    __prepareWebGL(): void;
    __createShader(): any;
    __createTexture(): any;
    __copyAudioDataToTexture(): void;
    __renderQuad(): void;
    render(): JSX.Element;
}
